### ISSUE TITLE
https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=Mmx1cDhzdW9vZ3F1NWIzMDgwczV1OWY2aG0gbmluYXdveXRoYWxlckBt&tmsrc=ninawoythaler%40gmail.com

### ISSUE THREAD

**Issue by nina-woythaler** [AnarchoTechNYC/NYCAnarchistEvents#14]
Please add the following event source to the calendar: https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=Mmx1cDhzdW9vZ3F1NWIzMDgwczV1OWY2aG0gbmluYXdveXRoYWxlckBt&tmsrc=ninawoythaler%40gmail.com

**Comment by fabacab** [comment]
This URL does not appear to be an event source, but rather a template for a specific event. Event sources look like public Google Calendar iCalendar feeds. As per the site footer, please refer to [the linked Google Support answer for more information about creating, managing, and sharing a public Google Calendar](https://support.google.com/calendar/answer/37083).

**Comment by nina-woythaler** [comment]
https://calendar.google.com/calendar/ical/roo.noises%40gmail.com/public/basic.ics
Sorry for noob behavior

**Comment by fabacab** [comment]
> Sorry for noob behavior

That's okay, we were all noobs once.

> https://calendar.google.com/calendar/ical/roo.noises%40gmail.com/public/basic.ics

As of this writing, all but one event on this calendar has already passed. It also appears to be a *private* calendar made public, showing events like "hold for co-work." You should double-check that this is your intention. If it is, you need to be mindful that all published events in the feed are going to show up on the web site. So:

* place events in the *future* on this calendar for it to have any meaningful effect in the context of this project.
* delete events from the calendar after they occur so as to maintain small, speedy downloads for all viewers.
* don't create events for private, behind-the-scenes organizing activities that make no sense to a viewing public.

At a minimum, you should [create a new calendar](https://support.google.com/calendar/answer/37095?hl=en) for the dedicated purpose of publishing event information. I'm not really comfortable publishing this source as is, nor would it really make sense to publish a source with only one event on it?

**Comment by nina-woythaler** [comment]
Oops - I meant to put it on a calendar with just that one event and failed.
If it wouldn't make sense to publish a source with only one event on it, what can I provide instead? We have this [instagram account](https://www.instagram.com/poetry_undressed/) and this [ticket link](https://poetryundressed.secretparty.io/) on an indie event website.

Here's a calendar feed with only the 1 event on it, in case that ends up being the best option: https://calendar.google.com/calendar/ical/ab42a68bc52eb56d34f1573849cf9abf8ebe7a15e9ea7e231cbba86e630aa382%40group.calendar.google.com/public/basic.ics

Thank you so much for your help.

**Comment by fabacab** [comment]
> We have this [instagram account](https://www.instagram.com/poetry_undressed/)

Instagram is by both technical implementation and site policy exactly the wrong choice, but…

> and this [ticket link](https://poetryundressed.secretparty.io/) on an indie event website.

…this site is particularly intriguing.

Technical musings follow. Feel free to skip to the end if you're not interested or if it's not relevant to you. I'm writing it out for posterity and so I have somewhere to point others to in the future so I don't have to re-explain the thought process here each time someone makes a request to include an event.

So, I've never heard of this SecretParty.io event ticketing platform before but after poking around it looks like it provides a rich API. Here's [your "Poetry Undressed" event data](https://api.secretparty.io/events/poetryundressed) in a much cleaner and easier to consume form. It's a very simple JSON response payload. Chef's kiss!

This means that if I write a sort of plugin for this site that can speak to and understand responses from Secret Party in order add support for *your* event, I can theoretically consume *all* events made by anyone who publishes their event at Secret Party. I vastly prefer this over a Google Calendar feed.

Implementing these sorts of third-party system translators to this site is not that hard because I've already defined a bunch of boilerplate patterns for doing so. I call these "event source plugins," and you can see the [currently supported event sources in the codebase, here](https://github.com/AnarchoTechNYC/NYCAnarchistEvents/tree/1bb310fa97fec8adbe94a9ec174b23064df93ee0/static/js/event-sources). What I really love about Secret Party in particular is that I don't have to workaround Cross-Origin Resource Sharing (CORS) restrictions, because their server is (correctly!) responding with an `Access-Control-Allow-Origin: *` HTTP response header; this means we don't need to use any of our own infrastructure to support the event publisher.

> Here's a [calendar feed with only the 1 event on it](https://calendar.google.com/calendar/ical/ab42a68bc52eb56d34f1573849cf9abf8ebe7a15e9ea7e231cbba86e630aa382%40group.calendar.google.com/public/basic.ics), in case that ends up being the best option.

This would work in a low-fi solution, but given the above discovery I'd like to instead work to support Secret Party more generally. I can write an implementation that adds your one event, but there are several problems with doing so, most important of which is that I'd be writing code that will be outdated in a week once your event passes.

I'm going to see if I can make some time to poke at the platform a little more fully to learn if there's a way I can add not a single event (since that by definition is not an event *source*) but rather all of the events by a given user account. Again, the whole purpose of an event *source* is that I *don't* have to do anything manual in order for a single, individual event to be published; that's the event publishers/promoters/etc. job. Doing things that way, people can just tell me who they are on the Secret Party platform, and I can "follow" whatever they post automatically.

Follow progress on the above at #15.
